### ISSUE TITLE
Exception in jScope when displaying empty signals in (X&Y) mode

### ISSUE THREAD

**Issue by merlea** [MDSplus/mdsplus#1298]
This is the exception raised:

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 0
	at jScope.Signal.showYZ(Signal.java:1174)
	at jScope.Signal.showYZ(Signal.java:1152)
	at jScope.Signal.setMode2D(Signal.java:1464)
	at jScope.Signal.setMode2D(Signal.java:1402)
	at jScope.jScopeMultiWave.Update(jScopeMultiWave.java:225)
	at jScope.jScopeWaveContainer$1.run(jScopeWaveContainer.java:865)

Looking at the Signal.java code, I guess one should check for zY2D being empty or smaller than idx.

This is present both in stable and alpha versions.

Antoine.

**Comment by merlea** [comment]
Fixed for me using latest alpha.
I am closing the issue.

Thanks,
Antoine.

**Comment by merlea** [comment]
Hello Gabriele,

Sorry but I was a bit too quick closing this issue.
I have been able to replicate the issue using simple expressions. Please see the configuration file attached (I had to rename it to .txt so that github allows me to upload it).
[empty.txt](https://github.com/MDSplus/mdsplus/files/2031785/empty.txt)

The error only appears for this particular value of mode_2D: yz(x) or "x&y" in the GUI.
If we change this to "y&time" or "y&x" then the exception vanishes.

Here is the exception text:
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at jScope.Signal.showYZ(Signal.java:1191)
	at jScope.Signal.showYZ(Signal.java:1152)
	at jScope.Signal.setMode2D(Signal.java:1464)
	at jScope.Signal.setMode2D(Signal.java:1402)
	at jScope.jScopeMultiWave.Update(jScopeMultiWave.java:225)
	at jScope.jScopeWaveContainer.UpdateAllWave(jScopeWaveContainer.java:825)
	at jScope.jScopeWaveContainer$UpdW.run(jScopeWaveContainer.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 0
	at jScope.Signal.showYZ(Signal.java:1191)
	at jScope.Signal.showYZ(Signal.java:1152)
	at jScope.Signal.setMode2D(Signal.java:1464)
	at jScope.Signal.setMode2D(Signal.java:1402)
	at jScope.jScopeMultiWave.Update(jScopeMultiWave.java:225)
	at jScope.jScopeWaveContainer$1.run(jScopeWaveContainer.java:865)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Thanks,
Antoine.

**Comment by merlea** [comment]
Fixed using alpha_release-7-42-3.
