### ISSUE TITLE
Cannot run TCL commands from python module.  Error: %LIB-F-KEYNOTFOU

### ISSUE THREAD

**Issue by fluffynukeit** [MDSplus/mdsplus#2428]
I am using mdsplus compiled from source.  I can execute TCL commands from the mdstcl console without any printed error.  However, seemingly any tcl command I try to execute from the MDSplus python module results in %LIB-F-KEYNOTFOU error, which (apparently) is not a python exception because there is no stack trace.  This happens whether I do it through the Tree object or the MDSplus module. TDI from the MDSplus module appears to work just fine.  I tried this with MDSplus 7.131.5 and 7.131.6.  See the demonstration below.

Also, perhaps related, is that when I try to dispatch on the action node using the python interface, I get a %TREE-E-BADRECORD error claiming the data is corrupted.  But I can explore the tree using jTraverser2 (also built from source) just fine without any apparent problems.

When using a pre-built MDSplus package, we don't experience these problems.  We are hoping to avoid pre-built packages, however, to enable auditing and traceability of our experimental infrastructure.  Do you have an idea of what would cause this error?  I am willing to track it down in detail but I have run out of leads.  I am hoping to at least get pointed in the right direction.  TYVM.

```
TCL> set tree fuze /shot=-1
TCL> set current fuze /increment
TCL> create pulse 0
TCL> set tree fuze /shot=0
TCL> exit

### Commands completed without error

zei@mdsplus:~/mdsplus-deployment/test$ ./result/bin/python
Python 3.8.9 (default, Apr  2 2021, 11:20:07) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from MDSplus import Tree
>>> t = Tree('fuze', 0)
>>> t.tcl('DO .ACTIONS:WR_SHOT_TIME')
Error: %LIB-F-KEYNOTFOU, Key not found

>>> t.tcl('set tree fuze /shot=0')
Error: %LIB-F-KEYNOTFOU, Key not found

>>> t.ACTIONS.WR_SHOT_TIME  # ← Auto complete worked here
.ACTIONS:WR_SHOT_TIME           
>>> import MDSplus
>>> MDSplus.tcl('set tree fuze /shot=0')
Error: %LIB-F-KEYNOTFOU, Key not found

>>> MDSplus.tdi('current_shot("fuze")')
211201019
>>> MDSplus.tcl('set tree fuze')
Error: %LIB-F-KEYNOTFOU, Key not found

>>> t.ACTIONS.WR_SHOT_TIME.dispatch()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/y2dd6rw7vgjbjn17frf23kzzv7l2iw7k-MDSplus-python-src/python/MDSplus/tree.py", line 1834, in dispatch
    a = self.record
  File "/nix/store/y2dd6rw7vgjbjn17frf23kzzv7l2iw7k-MDSplus-python-src/python/MDSplus/tree.py", line 1511, in record
    return self.getRecord()
  File "/nix/store/y2dd6rw7vgjbjn17frf23kzzv7l2iw7k-MDSplus-python-src/python/MDSplus/tree.py", line 1946, in getRecord
    raise _exc.MDSplusException(status)
MDSplus.mdsExceptions.TreeBADRECORD: %TREE-E-BADRECORD, Data corrupted: cannot read record
>>> 
```

**Comment by fluffynukeit** [comment]
I resolved this issue.  The problem was related to trying to load dynamic libraries at runtime.  The env vars used to control the library load location are MDSPLUS_DIR, MDSPLUS_LIBRARY_PATH, and (possibly) LD_LIBRARY_PATH.  My issue was that these env vars were being set correctly when running commands like mdstcl but not when invoking the python interpreter.  After synchronizing the env vars, the python interface started working properly.  Closing.
