### ISSUE TITLE
MDSplus8 can not add members to nodes with long names in python

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2690]
**Affiliation**
MIT

**Version(s) Affected**
```
[jas@ip-10-7-162-225 mdsquartz]$ mdstcl
TCL> show version


MDSplus version: 7.139.60
----------------------
  Release:  mdsplus8_release_7.139.60
  Browse:   https://github.com/MDSplus/mdsplus/tree/mdsplus8_release_7.139.60
  Download: https://github.com/MDSplus/mdsplus/archive/mdsplus8_release_7.139.60.tar.gz
```

**Platform**
amazon linux
**Describe the bug**
When editing a tree in python I add structure node with a long name.  I then try to add a member to that node and it throws MDSplus.mdsExceptions.TreeNNF: %TREE-W-NNF, Node Not Found
```
>>> import MDSplus
Warning:
  The MDSplus python module version (cmake_release_7.139.47) does not match
  the version of the installed MDSplus libraries (mdsplus8_release_7.139.60).
  Upgrade the module using the mdsplus/python/MDSplus directory of the
  MDSplus installation or set PYTHONPATH=/usr/local/mdsplus/python.
>>> MDSplus.__file__
'/data/home/jas/mdsplus-cmake/build/amazonlinux2/cmake/usr-local-mdsplus/python/MDSplus/__init__.py'
>>> tree = MDSplus.Tree('magtest', 1, 'edit')
>>> parent = tree.addNode('.this_has_a_long_name', 'STRUCTURE')
>>> parent
.THIS_HAS_A_LONG_NAME
>>> parent.addNode('short_name', 'NUMERIC')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/home/jas/mdsplus-cmake/build/amazonlinux2/cmake/usr-local-mdsplus/python/MDSplus/tree.py", line 1685, in addNode
    return self.tree.addNode(name, usage)
  File "/data/home/jas/mdsplus-cmake/build/amazonlinux2/cmake/usr-local-mdsplus/python/MDSplus/tree.py", line 767, in addNode
    _exc.checkStatus(
  File "/data/home/jas/mdsplus-cmake/build/amazonlinux2/cmake/usr-local-mdsplus/python/MDSplus/mdsExceptions.py", line 92, in checkStatus
    raise exception
MDSplus.mdsExceptions.TreeNNF: %TREE-W-NNF, Node Not Found
>>>

**Comment by mwinkel-dev** [comment]
The above code fragment works fine on Ubuntu 20.   Following output is from a Docker build using `ubuntu-20-x86_64`.

```
$ python3
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MDSplus
>>> tree = MDSplus.Tree('magtest', 100, 'edit')
>>> parent = tree.addNode('.this_has_a_long_name', 'STRUCTURE')
>>> parent
.THIS_HAS_A_LONG_NAME
>>> parent.addNode('short_name', 'NUMERIC')
.THIS_HAS_A_LONG_NAME:SHORT_NAME
>>> tree.write()
>>> tree.close()
>>> quit()
$ 
$ 
$ 
$ mdstcl
TCL> set tree magtest /shot=100
TCL> dir ***

\MAGTEST::TOP

 :A234567890B234567890C234567890 :NUM1

  THIS_HAS_A_LONG_NAME

Total of 3 nodes.

\MAGTEST::TOP.THIS_HAS_A_LONG_NAME

 :SHORT_NAME

Total of 1 node.


Grand total of 4 nodes.
TCL> quit
```

Tomorrow, will see if the bug can be reproduced on `amazonlinux`.

**Comment by joshStillerman** [comment]
Your example fails on my amazonlinux:
```
>>> tree = MDSplus.Tree('magtest', 100, 'new')
>>> parent = tree.addNode('.this_has_a_long_name', 'STRUCTURE')
>>> parent.addNode('short_name', 'NUMERIC')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/home/jas/mdsplus-cmake/build/amazonlinux2/cmake/usr-local-mdsplus/python/MDSplus/tree.py", line 1685, in addNode
    return self.tree.addNode(name, usage)
  File "/data/home/jas/mdsplus-cmake/build/amazonlinux2/cmake/usr-local-mdsplus/python/MDSplus/tree.py", line 767, in addNode
    _exc.checkStatus(
  File "/data/home/jas/mdsplus-cmake/build/amazonlinux2/cmake/usr-local-mdsplus/python/MDSplus/mdsExceptions.py", line 92, in checkStatus
    raise exception
MDSplus.mdsExceptions.TreeNNF: %TREE-W-NNF, Node Not Found
>>> MDSplus.__file__
'/data/home/jas/mdsplus-cmake/build/amazonlinux2/cmake/usr-local-mdsplus/python/MDSplus/__init__.py'
>>> 
```

**Comment by joshStillerman** [comment]
ohh wait not sure this is the correct .py. checking now
Noop - 
unless I am really confused, it is broken even with the right python files:
```
[jas@ip-10-7-162-225 mdsquartz]$ python
Python 3.10.10 (main, Mar 30 2023, 20:33:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MDSplus
>>> MDSplus.__file__
'/data/home/jas/mdsquartz/usr-local-mdsplus/python/MDSplus/__init__.py'
>>> 
>>> t = MDSplus.Tree('magtest', 100, 'new')
>>> parent = t.addNode('averylongnodename', 'structure')
>>> member = parent.addNode('shortmem', 'numeric')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/home/jas/mdsquartz/usr-local-mdsplus/python/MDSplus/tree.py", line 1706, in addNode
    return self.tree.addNode(name, usage)
  File "/data/home/jas/mdsquartz/usr-local-mdsplus/python/MDSplus/tree.py", line 773, in addNode
    _exc.checkStatus(
  File "/data/home/jas/mdsquartz/usr-local-mdsplus/python/MDSplus/mdsExceptions.py", line 94, in checkStatus
    raise exception
MDSplus.mdsExceptions.TreeNNF: %TREE-W-NNF, Node Not Found
>>> parent
.AVERYLONGNODENAME
>>> mem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'mem' is not defined
>>> 
```
and
```
>>> MDSplus.__version__
'mdsplus8_release_7.139.60'
>>> 
```
Finally, if the parent's name is short then all is well:
```
[jas@ip-10-7-162-225 mdsquartz]$ python
Python 3.10.10 (main, Mar 30 2023, 20:33:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MDSplus
>>> t = MDSplus.Tree('magtest', 100, 'new')
>>> parent = t.addNode('parent', 'structure')
>>> member = parent.addNode('shortmem', 'numeric')
>>> 
```

**Comment by mwinkel-dev** [comment]
The test also worked fine when run in a Docker container that has `amazonlinux-2-x86_64`.   Output is given below.

```
bash-4.2$ cat /etc/os-release | fgrep NAME
NAME="Amazon Linux"
PRETTY_NAME="Amazon Linux 2"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
bash-4.2$ 
bash-4.2$ 
bash-4.2$ export default_tree_path=/tmp/xmw_trees
bash-4.2$ mdstcl
TCL> edit magtest /shot=100 /new
TCL> add node num1/usage=numeric
TCL> add node a234567890b234567890c234567890/usage=numeric
TCL> dir

\MAGTEST::TOP

 :A234567890B234567890C234567890 :NUM1

Total of 2 nodes.
TCL> write
TCL> close
TCL> quit
bash-4.2$
bash-4.2$
bbash-4.2$ python3
Python 3.8.16 (default, Aug 30 2023, 23:19:34) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MDSplus
>>> tree = MDSplus.Tree('magtest', 100, 'edit')
>>> parent = tree.addNode('.this_has_a_long_name', 'STRUCTURE')
>>> parent
.THIS_HAS_A_LONG_NAME
>>> parent.addNode('short_name', 'NUMERIC')
.THIS_HAS_A_LONG_NAME:SHORT_NAME
>>> tree.write()
>>> tree.close()
>>> quit
Use quit() or Ctrl-D (i.e. EOF) to exit
>>> quit()
bash-4.2$ 
bash-4.2$ 
bash-4.2$ mdstcl
TCL> set tree magtest /shot=100
TCL> dir ***

\MAGTEST::TOP

 :A234567890B234567890C234567890 :NUM1

  THIS_HAS_A_LONG_NAME

Total of 3 nodes.

\MAGTEST::TOP.THIS_HAS_A_LONG_NAME

 :SHORT_NAME

Total of 1 node.


Grand total of 4 nodes.
TCL> quit
```

**Comment by mwinkel-dev** [comment]
Repeated the test in the `amazonlinux-2-x86_64` Docker container used by the Jenkins build system.   Only issue is that after the `make install` and `source $MDSPLUS_DIR/setup.sh` steps, was necessary to do the following:

```
export LD_LIBRARY_PATH=$MDSPLUS_DIR/lib64:$LD_LIBRARY_PATH
export PYTHONPATH=$MDSPLUS_DIR/python:$PYTHONPATH
```

Anyway, the results were identical to the that shown in the previous post.   No problems found when running the test inside the Docker container.

Next step of the investigation will be to repeat the tests on a VM that has the official `Amazon Linux 2` distro as its OS.

**Comment by mwinkel-dev** [comment]
This issue has been resolved by @joshStillerman.

There are two formats for MDSplus files: 12-char and 63-char.   Mdsplus v7 and earlier has node names with a maximum of 12 visible characters (i.e., not counting trailing null characters).   Mdsplus v8 has node names with a maximum of 63 visible characters.

This issue was the result of using mdsplus8 to edit 12-char trees.   When mdsplus8 reads a 12-char file it then does in-memory expansion to the 63-char format.   Thus, the user can edit the in-memory tree by adding nodes with long names.   But when the tree is written to disk, the long names are truncated and the file is written in 12-char format.

Which can result in workflows that are quite confusing to the user.   It is natural for users to assume that if they are able to add a node with a long name that they are indeed editing 63-char tree files; they don't expect the truncation to 12-char files with the trees are written to disk.

When Josh started over with 63-char trees on disk, everything worked fine.   Thus closing this issue.

Also will create a new feature issue to cover the broader issue of mdsplus8 editing 12-char trees.

**Comment by mwinkel-dev** [comment]
For the sake of completeness, created a new VM with a freshly downloaded image of `Amazon Linux 2` (from the AWS web site).   Repeated the test with 63-char trees and all worked fine.
