### ISSUE TITLE
closeAllTrees() fails for thin client in python

### ISSUE THREAD

**Issue by lajz** [MDSplus/mdsplus#2708]
**Affiliation**
MIT PSFC

**Version(s) Affected**
TBD, likely alpha

**Platform**
ubuntu 20 or 22 (mfe workstations)

**Describe the bug**
The following exception is raised
```
 File "/usr/local/mdsplus/python/MDSplus/connection.py", line 269, in closeAllTrees
    self.get("_i=0;WHILE(IAND(TreeClose(),1)) _i++;_i")
  File "/usr/local/mdsplus/python/MDSplus/connection.py", line 325, in get
    return self.conn.get(exp, *args, **kwargs)
  File "/usr/local/mdsplus/python/MDSplus/connection.py", line 214, in get
    retSerialized = self._get_answer(timeout)
  File "/usr/local/mdsplus/python/MDSplus/connection.py", line 142, in _get_answer
    _exc.checkStatus(_GetAnswerInfoTO(self.conid, dtype, length, ndims,
  File "/usr/local/mdsplus/python/MDSplus/mdsExceptions.py", line 94, in checkStatus
    raise exception
MDSplus.mdsExceptions.TdiSYNTAX: %TDI-E-SYNTAX, Bad punctuation or misspelled word or number
```

**To Reproduce**
1. Go to CMod private network
2. Run
```
from MDSplus import Connection
conn = Connection('alcdata-new')
conn.openTree("pcs", shot=shot_id)
conn.closeAllTrees()
```

**Expected behavior**
All trees should be closed for the connection.

**Comment by mwinkel-dev** [comment]
Was able to easily reproduce the problem with Python thin-client `closeAllTrees()` using this configuration:
- current MDSplus alpha
- Ubuntu 20
- and two different MDSplus archive servers

Also confirmed that there were no problems using the related method, `closeTree()`.

**Comment by mwinkel-dev** [comment]
We should check the Python regression tests to see if `closeAllTrees()` is tested.   And if not, should add that to the tests.

**Comment by mwinkel-dev** [comment]
Was unable to reproduce this issue using the following version of MDSplus on Ubuntu 24 x86-64.

```
$ mdstcl
TCL> show version


MDSplus version: 7.151.0
----------------------
  Release:  alpha_release-7-151-0
  Date:     Tue Mar 25 22:00:25 UTC 2025
  Browse:   https://github.com/MDSplus/mdsplus/tree/alpha_release-7-151-0
  Download: https://github.com/MDSplus/mdsplus/releases/tag/alpha_release-7-151-0

TCL> quit
$
$
$ python3
Python 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MDSplus as mds
>>> c = mds.Connection('alcdata-archives')
>>> t = c.openTree('cmod',1090909009)
>>> c.closeAllTrees()
>>> quit()
```

This is the exact code that JoshL used in the original bug report.

```
$ python3
Python 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> shot_id = 1090909009
>>> from MDSplus import Connection
>>> conn = Connection('alcdata-new')
>>> conn.openTree("pcs", shot=shot_id)
>>> conn.closeAllTrees()
>>> quit()
```

**Comment by mwinkel-dev** [comment]
@gtrevisan -- Which branch (stable or alpha) of MDSplus have you installed on your computer and what is its version?

**Comment by gtrevisan** [comment]
I was using the standard alpha from the MFE WSs.
I saw this at a time during which I was trying many different things, so I'm not sure I can reproduce it easily.

are you able to take a look at the above stack trace and investigate from there?
in the mean time I am avoiding `closeAllTrees` so I won't see this again, but the bug is definitely there.

**Comment by mwinkel-dev** [comment]
Hi @gtrevisan -- Thanks for the information.   In light of that news, I will experiment with the `alpha` branch.

There have been some recent PRs that might have fixed this problem.   More investigation will be done to determine if that is the case.

**Comment by mwinkel-dev** [comment]
If the `mdsip` connection is trashed, then `closeAllTrees()` will fail.  This scenario is related to Issue #2901 and is illustrated below.   (The output is from `alpha` on Ubuntu 24 x86-64 running against the C-Mod archive server.)   Note though that this scenario generates a `MDSPLUS-E-ERROR` condition, but the original bug report generated a `TDI-E-SYNTAX` error.

```
$ python3                                          
Python 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MDSplus
>>> c = MDSplus.Connection("alcdata-archives")
>>> ok = 1150805012
>>> ko = 1150528006
>>> c.openTree("magnetics", ok)
>>> print(len(c.get(r"\ip")))
14336
>>> c.openTree("engineering", ko)
>>> c.get(r"\top.results:netpow")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/mdsplus/python/MDSplus/connection.py", line 319, in get
    return self.conn.get(exp, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/mdsplus/python/MDSplus/connection.py", line 213, in get
    return self._get_answer(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/mdsplus/python/MDSplus/connection.py", line 142, in _get_answer
    _exc.checkStatus(_GetAnswerInfoTO(self.conid, dtype, length, ndims,
  File "/usr/local/mdsplus/python/MDSplus/mdsExceptions.py", line 92, in checkStatus
    raise exception
MDSplus.mdsExceptions.MDSplusERROR: %MDSPLUS-E-ERROR, Error
>>> c.closeAllTrees()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/mdsplus/python/MDSplus/connection.py", line 265, in closeAllTrees
    self.get("_i=0;WHILE(IAND(TreeClose(),1)) _i++;_i")
  File "/usr/local/mdsplus/python/MDSplus/connection.py", line 319, in get
    return self.conn.get(exp, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/mdsplus/python/MDSplus/connection.py", line 209, in get
    _exc.checkStatus(_SendArg(self.conid, 0, 14, num,
  File "/usr/local/mdsplus/python/MDSplus/mdsExceptions.py", line 92, in checkStatus
    raise exception
MDSplus.mdsExceptions.MDSplusERROR: %MDSPLUS-E-ERROR, Error
>>> 
```

**Comment by mwinkel-dev** [comment]
Hi @gtrevisan -- If you encounter the `closeAllTrees()` error again, please post the traceback to this Issue.   I'm curious if you are encountering the `TDI-E-SYNTAX` variant of the problem or not.

**Comment by mwinkel-dev** [comment]
According to @gtrevisan, the `TDI-E-SYNTAX` problem arose last week.   The debug log file from that incident is now being studied.

**Comment by mwinkel-dev** [comment]
Opened 100 shots and read `\ip` from each shot, then did a `closeAllTrees()`.   Repeated that experiment several times and did not encounter any errors.

Therefore, conjecturing that this `TDI-E-SYNTAX` error is either dependent on the trees opened and/or Python threading.   Regardless, it is much harder to trigger this bug than it was back on 9-Feb-2024.

**Comment by mwinkel-dev** [comment]
The new conjecture is that this bug might be caused by the `TreeShr->TreeClose()` in the `CloseTreeRemote()` function of `treeshr/RemoteAccess.c`.   If the `dblist->shotid` and/or `tree` contains garbage, perhaps it would generate the `TDI-E-SYNTAX` error when the `MdsValue()` is evaluated by the server.

[TreeClose](https://github.com/MDSplus/mdsplus/blob/16549d875c108bf9f53ce116b9665ee0f495345b/treeshr/RemoteAccess.c#L337)

**Comment by mwinkel-dev** [comment]
Hi @gtrevisan,

This issue was filed by Josh Lorincz.   I am unable to reproduce the bug when the client is a developer build of the alpha branch from around December 2025.  Have you encountered any recent problems with the `closeAllTrees()`?   If not, is it OK if this issue is closed?

**Comment by gtrevisan** [comment]
the bug was definitely sneaky and tough to reproduce, but I did see it many times in the past.

since my last bump, though, I did my best to implement technical fail-safes within DisruptionPy to decouple users from MDSplus oddities such as this.
as a consequence, I won't be able to investigate further -- I doubt it's fixed, but feel free to close this.

my suggestion is to keep a list of all these corrupted shots for which testing should definitely be more thorough.

**Comment by mwinkel-dev** [comment]
Hi @gtrevisan -- Thanks for the update.   It is useful to learn that the bug is still likely lurking in the code.   I will therefore leave this issue open for a few more weeks.

It was easy for me to reproduce the bug when Josh L. first reported it.  But with newer MDSplus releases I was unable to trigger it, which I hoped meant that the bug had vanished.   

However, as that is not the case, my new conjecture is that it likely involves a cross-version incompatibility -- that perhaps the bug is triggered when a new version of MDSplus on the client interacts with an old version of MDSplus on the archive server.
