### ISSUE TITLE
tags with 24 characters can be created and listed but not used

### ISSUE THREAD

**Issue by cenkoloji** [MDSplus/mdsplus#2821]
**Affiliation**
EPFL

**Version(s) Affected / Platform(s)**
Rocky Linux 9 - mdsplus-alpha 7.139-60
RHEL7 - mdsplus-stable 7.142.81
CentOS 8 - mdsplus-stable 7.131-5

**Installation Method(s)**
yum/dnf

**Describe the bug**
Tags with 24 characters can be created, or seen by `Tcl('dir /tag')`, but node can't be retrieved by tag

**To Reproduce**
python
```python
#!/usr/bin/env python

import MDSplus
t = MDSplus.Tree('cenktest',-1,"NEW")

nodes_tags = {"mynode{:02d}".format(n):"a"*n for n in range(1,26)}

for node,tag in dict(nodes_tags).items():
    try:
        n = t.addNode(node,usage='SIGNAL')
        n.addTag(tag)
    except:
        print("Can't create node,tag:{},{}".format(node,tag))
        nodes_tags.pop(node)

t.write()
t.close()

print()
t = MDSplus.Tree('cenktest',-1)

for node,tag in nodes_tags.items():
    try:
        t.getNode("\\" + tag)
    except Exception as ex:
        print("{} - {:30s} -> Can't get node from tag".format(node,tag));
        print(ex)
```
output:
```
Can't create node,tag:mynode25,aaaaaaaaaaaaaaaaaaaaaaaaa

mynode24 - aaaaaaaaaaaaaaaaaaaaaaaa       -> Can't get node from tag
%TREE-W-NNF, Node Not Found

```
Here I demonstrate that tag creation works as expected, up to 24 characters, but retrieval doesn't work for 24 characters.

**Comment by merlea** [comment]
It seems the error is when calling `TreeFindNode` with the 24 character tag name. It always returns a "Node Not Found" status in this case.

Using `gdb`, it seems the failing step is `WildParse` where the search term is correctly identified as "TAG_TREE" but the search string has been shortened by one character (see at the end of the snipped below). I couldn't go further into debugging the Parser itself.

```
(gdb) bt
#0  FindTags (dblist=0x5555555c5380, info=0x5555555c5440, treenum=0, tagname=0x5555555aacf7 "ABCDEFGHIJKLMNOPQRSTUVW", tail=0x7ffffffee1f8) at ../../treeshr/TreeFindNode.c:445
#1  0x00007ffff7f696db in FindTagWild (dblist=0x5555555c5380, term=0x5555555c48d0, tail=0x7ffffffee3a0) at ../../treeshr/TreeFindNode.c:517
#2  0x00007ffff7f69171 in Find (dblist=0x5555555c5380, term=0x5555555c48d0, start=0x7ffff7ffa200, tail=0x7ffffffee3a0) at ../../treeshr/TreeFindNode.c:399
#3  0x00007ffff7f68d51 in Search (dblist=0x5555555c5380, ctx=0x7ffffffee3c0, term=0x5555555c48d0, start=0x7ffff7ffa200, tail=0x7ffffffee3a0) at ../../treeshr/TreeFindNode.c:295
#4  0x00007ffff7f68c01 in _TreeFindNodeRelative (dbid=0x5555555c5380, path=0x5555555c5650 "\\TEST::abcdefghijklmnopqrstuvwx", startnid=0, outnid=0x7ffffffee550) at ../../treeshr/TreeFindNode.c:257
#5  0x00007ffff7f68ab2 in _TreeFindNode (dbid=0x5555555c5380, path=0x5555555c5650 "\\TEST::abcdefghijklmnopqrstuvwx", outnid=0x7ffffffee550) at ../../treeshr/TreeFindNode.c:218
#6  0x00007ffff7f68682 in TreeFindNode (path=0x5555555c5650 "\\TEST::abcdefghijklmnopqrstuvwx", outnid=0x7ffffffee550) at ../../treeshr/TreeFindNode.c:121
#7  0x00007ffff7b632b3 in treefindnode (dat_ptr=0x5555555c4b50 "\\TEST::abcdefghijklmnopqrstuvwxx\034\001BER\")", len=31, nid=0x7ffffffee550) at ../../tdishr/TdiGetNci.c:296
#8  0x00007ffff7b63566 in Tdi1GetNci (opcode=OPC_GETNCI, narg=2, list=0x7ffffffee9f8, out_ptr=0x7ffffffee780) at ../../tdishr/TdiGetNci.c:340
#9  0x00007ffff7b88f9f in TdiIntrinsic (opcode=OPC_GETNCI, narg=2, list=0x5555555aad78, out_ptr=0x7ffffffef480) at ../../tdishr/TdiIntrinsic.c:255
#10 0x00007ffff7b5a520 in Tdi1Evaluate (opcode=OPC_EXECUTE, narg=1, list=0x7ffffffef2e8, out_ptr=0x7ffffffef480) at ../../tdishr/TdiEvaluate.c:157
#11 0x00007ffff7ac6329 in Tdi1Execute (opcode=OPC_EXECUTE, narg=1, list=0x7ffffffef6f8, out_ptr=0x7ffffffef480) at ../../tdishr/TdiCompile.c:174
#12 0x00007ffff7b88f9f in TdiIntrinsic (opcode=OPC_EXECUTE, narg=1, list=0x7ffffffeff60, out_ptr=0x555555559030 <ans>) at ../../tdishr/TdiIntrinsic.c:255
#13 0x00007ffff7b012ef in TdiExecute (first=0x555555559080 <expr_dsc>) at /home/amerle/source/mdsplus/build/../include/opcbuiltins.h:184
#14 0x00005555555560d0 in main (argc=1, argv=0x7fffffffca78) at ../../tdic/tdic.c:381
(gdb) frame 3
#3  0x00007ffff7f68d51 in Search (dblist=0x5555555c5380, ctx=0x7ffffffee3c0, term=0x5555555c48d0, start=0x7ffff7ffa200, tail=0x7ffffffee3a0) at ../../treeshr/TreeFindNode.c:295
295	  NODELIST *nodes = term ? Find(dblist, term, start, tail) : NULL;
(gdb) p ctx->wildcard
$27 = 0x5555555c3b90 "\\TEST::abcdefghijklmnopqrstuvwx"
(gdb) p *(ctx->terms)
$28 = {search_type = 258, term = 0x5555555c3b60 "\\TEST::ABCDEFGHIJKLMNOPQRSTUVW", next = 0x5555555c48a0, start_node = 0x78777675747372}
```

**Comment by merlea** [comment]
Actually it seems the error is in the definition of the TAG and TAG_TREE for the lexer where 23 characters were used and not 24.

I have opened a Pull Request with a possible solution.

**Comment by mwinkel-dev** [comment]
Hi @cenkoloji and @merlea -- Thanks for reporting this issue and also for the PR!   I will look at both later today.
