### ISSUE TITLE
Data.compile() produces incorrect output under Python 3

### ISSUE THREAD

**Issue by taerath** [MDSplus/mdsplus#783]
Consider the following script:

```
#!/usr/bin/env python
import MDSplus
import os

TREENAME = 'test_rtpcs'
os.environ[TREENAME + '_path'] = TREENAME

if not os.path.exists(TREENAME):
    os.mkdir(TREENAME)

tree = MDSplus.Tree(TREENAME, -1, 'New')
ch_node = tree.addNode(':signal', usage='signal')
data_str = 'BUILD_SIGNAL($VALUE, :signal:data, :signal:time)'
ch_node.putData(MDSplus.Data.compile(data_str))
tree.write()
```

When run under Python 2.x it works as expected: the `signal` node contains a signal constructed from the `signal:data` and `signal:time` nodes.

When run under Python 3 under Windows, the script completes without errors, but the contents of the `script` node are wrong. Somehow, the node names end up being bytes representations:

```
BUILD_SIGNAL($VALUE, b'\\TOP:signal:data', b'\\TOP::signal:time')
```

When run under Python 3 under Linux, the script fails with:

```
Traceback (most recent call last):
  File "/home/nikratio/.local/lib/python3.5/site-packages/MDSplus/_descriptor.py", line 369, in _getValue
    return _scalar.makeScalar(_dtypes.mdsdtypes(self.dtype).toNumpy()(_C.cast(self.pointer,_C.POINTER(_dtypes.mdsdtypes(self.dtype).toCtype())).contents.value))
  File "/home/nikratio/.local/lib/python3.5/site-packages/MDSplus/_mdsdtypes.py", line 115, in toNumpy
    raise TypeError('Cannot convert '+str(self.dtype)+' to numpy type')
TypeError: Cannot convert 193 to numpy type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create_tree3.py", line 14, in <module>
    ch_node.putData(MDSplus.Data.compile(data_str))
  File "/home/nikratio/.local/lib/python3.5/site-packages/MDSplus/mdsdata.py", line 488, in compile
    return _mimport('_tdishr',1).TdiCompile(expr,args)
  File "/home/nikratio/.local/lib/python3.5/site-packages/MDSplus/_tdishr.py", line 53, in TdiCompile
    return xd.value
  File "/home/nikratio/.local/lib/python3.5/site-packages/MDSplus/_descriptor.py", line 568, in _getValue
    return _C.cast(_C.pointer(self),_C.POINTER(descriptor)).contents.value
  File "/home/nikratio/.local/lib/python3.5/site-packages/MDSplus/_descriptor.py", line 350, in _getValue
    return self.pointer.contents.value
  File "/home/nikratio/.local/lib/python3.5/site-packages/MDSplus/_descriptor.py", line 460, in _getValue
    arglist.append(ans.dscptrs[i].contents.value)
  File "/home/nikratio/.local/lib/python3.5/site-packages/MDSplus/_descriptor.py", line 400, in _getValue
    return _treenode.TreePath(_C.cast(self.pointer,_C.POINTER(_C.c_char*self.length)).contents.value,descriptor.tree)
  File "/home/nikratio/.local/lib/python3.5/site-packages/MDSplus/treenode.py", line 1132, in __init__
    self.tree_path=_data.makeData(path);
  File "/home/nikratio/.local/lib/python3.5/site-packages/MDSplus/mdsdata.py", line 95, in makeData
    raise TypeError('Cannot make MDSplus data type from type: %s' % (str(type(value)),))
TypeError: Cannot make MDSplus data type from type: <class 'bytes'>
```

**Comment by taerath** [comment]
Hmm. I tried to confirm that this fixes the problem, but the current alpha just crashes on me (also before the fix):

```
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/version.py", line 45, in load_library
    return C.CDLL(libnam)
  File "/opt/anaconda3/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/anaconda3/bin/../lib/libreadline.so.6: undefined symbol: PC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/version.py", line 48, in load_library
    return C.CDLL(name)
  File "/opt/anaconda3/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: Mdsdcl: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/treenode.py", line 3, in _mimport
    return __import__(name, globals(), level=level)
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/mdsdcl.py", line 14, in <module>
    _mdsdcl=_ver.load_library('Mdsdcl')
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/version.py", line 50, in load_library
    return C.CDLL(os.path.basename(libnam))
  File "/opt/anaconda3/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/anaconda3/bin/../lib/libreadline.so.6: undefined symbol: PC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_treeshr.py", line 3, in _mimport
    return __import__(name, globals(), level=level)
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/treenode.py", line 17, in <module>
    _mdsdcl=_mimport('mdsdcl')
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/treenode.py", line 5, in _mimport
    return __import__(name, globals())
ImportError: No module named 'mdsdcl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/tree.py", line 3, in _mimport
    return __import__(name, globals(), level=level)
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_treeshr.py", line 12, in <module>
    _treenode=_mimport('treenode')
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_treeshr.py", line 5, in _mimport
    return __import__(name, globals())
ImportError: No module named 'treenode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_tdishr.py", line 3, in _mimport
    return __import__(name, globals(), level=level)
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/tree.py", line 12, in <module>
    _treeshr=_mimport('_treeshr')
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/tree.py", line 5, in _mimport
    return __import__(name, globals())
ImportError: No module named '_treeshr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_descriptor.py", line 3, in _mimport
    return __import__(name, globals(), level=level)
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_tdishr.py", line 12, in <module>
    _tree=_mimport('tree')
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_tdishr.py", line 5, in _mimport
    return __import__(name, globals())
ImportError: No module named 'tree'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/mdsdata.py", line 3, in _mimport
    return __import__(name, globals(), level=level)
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_descriptor.py", line 760, in <module>
    _tdishr=_mimport('_tdishr')
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_descriptor.py", line 5, in _mimport
    return __import__(name, globals())
ImportError: No module named '_tdishr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/apd.py", line 3, in _mimport
    return __import__(name, globals(), level=level)
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/mdsdata.py", line 803, in <module>
    _descriptor=_mimport('_descriptor')
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/mdsdata.py", line 5, in _mimport
    return __import__(name, globals())
ImportError: No module named '_descriptor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_loadglobals.py", line 4, in loadmod
    return __import__(name, gbls, level=1)
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/apd.py", line 11, in <module>
    _data=_mimport('mdsdata')
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/apd.py", line 5, in _mimport
    return __import__(name, globals())
ImportError: No module named 'mdsdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "py3bug.py", line 2, in <module>
    import MDSplus
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/__init__.py", line 37, in <module>
    _mimport('_loadglobals').load(globals())
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_loadglobals.py", line 17, in load
    loadmod_full(mod,gbls)
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_loadglobals.py", line 9, in loadmod_full
    mod=loadmod(name)
  File "/home/nikratio/.local/lib/python3.5/site-packages/mdsplus_unknown-1.0.0-py3.5.egg/MDSplus/_loadglobals.py", line 6, in loadmod
    return __import__(name, gbls)
ImportError: No module named 'apd'
```
