### ISSUE TITLE
jTraverser "no JavaMds in java.library.path" problem

### ISSUE THREAD

**Issue by wbb12** [MDSplus/mdsplus#995]
#I have installed MDSplu in the Ubuntu 16.04 LTS , but when I open the jTraverser in the terminal and try to open and edit a tree I have just created on this computer, the  jTraverser has no response and the terminal shows a info ‘no JavaMds in java.library.path’. The detailed info from the terminal is listed bellow. 

I have install the openjdk-8 successfully.  I want to know how to fix the problem and edit the tree by  jTraverser.

can any one has ever  encountered this problem and know how to fix it? Thank you!
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no JavaMds in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at Database.<clinit>(Database.java:16)
	at Tree.open(Tree.java:357)
	at Tree.open_ok(Tree.java:326)
	at Tree.actionPerformed(Tree.java:1063)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
cException in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class Database
	at Tree.open(Tree.java:357)
	at Tree.open_ok(Tree.java:326)
	at Tree.actionPerformed(Tree.java:1063)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by zack-vii** [comment]
I have seen this error many times and it is in most cases due to a mixture of 64bit and 32 bit versions of java vs MDSplus. As the error message states the program is not satisfied with the link to an external library that is shipped with MDSplus. Eventually it cannot be found because the LD_LIBRARYPATH is configured incorrectly. you may want to locate the libJavaMds.so and include its parent directory to the LD_LIBRARYPATH before launching jTraverser. I hope this helps

**Comment by tfredian** [comment]
The jTraverser script script sets the java.library.path property which should enable java to find the libJavaMds.so library assuming the MDSplus environment variables are defined in the process starting jTraverser. The script requires the MDSPLUS_DIR environment variable to specify the root directory of the MDSplus installation. If this is a new install of MDSplus it is possible that some running processes may not have the required environment variables so you may have to log out and log back in to get them initialized correctly. You should make sure /usr/local/mdsplus/lib/libJavaMds.so exists and that its arch matches that of the jvm. Ubuntu is pretty much a single architecture OS but you can check to these by doing:

 $ file /usr/local/mdsplus/lib/libJavaMds.so 
 $ file $(readlink -f $(which java))

They should both be 64-bit or they should both be 32-bit but not one of each.

**Comment by wbb12** [comment]
I have rechecked the environment variables and the architecture of the Mdsplus and  java and get the result below. it seems that the environment variables are set correctly and the architecture are both 64 bits. However, when I launch the jTraverser by terminal again , the problem still occurred.
 
******@******:~$ echo $LD_LIBRARYPATH
/usr/local/mdsplus/java/classes
******@******:~$ echo $MDSPLUS_DIR
/usr/local/mdsplus
******@******:~$ file /usr/local/mdsplus/lib/libJavaMds.so
/usr/local/mdsplus/lib/libJavaMds.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=4b856cd0402441262181033520431af68ffa434a, not stripped
******@******:~$ file $(readlink -f $(which java))
/usr/lib/jvm/java-8-oracle/jre/bin/java: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.9, BuildID[sha1]=c90f19ee0af98c47ccaa7181853cfd14867bc931, not stripped

**Comment by tfredian** [comment]
Are other MDSplus applications working on your system? i.e. mdstcl, tditest?
I just noticed that on my Redhat system the core MDSplus libraries seemed to be linked to a libraw1394.so library which must be a bug in the configure/Makefile's of MDSplus. If this is the case on Ubuntu then it is likely that there was no dependency on the package providing the library and it may not be installed on your system. Can you try the command:

    ldd /usr/local/mdsplus/lib/libJavaMds.so

and see if there are any missing libraries that it depends on? If so you could try installing packages that provide the missing libraries. I will try to see why libraw1394 is being linked in to libraries that it is not used and attempt to fix this for future releases.

**Comment by gjhartwell** [comment]
I realize this thread has been closed and apparently fixed per #1039, but I'm seeing the same behavior as mentioned by wbb12 when I try to run jTraverser.

---- I have a fresh install of Ubuntu 16.04 (up-to-date), and MDSplus_7.7.7 from October 12, 2017. 
---- I've verified that LD_LIBRARY_PATH (and LD_LIBRARYPATH) point to /usr/local/mdsplus/lib
---- I've verified that both java and the mdsplus systems are 64-bit
---- I've verified that there are no missing dependencies for libJavaMds.so
---- I've verified that MDSPLUS_DIR is set to /usr/local/mdsplus 
---- I've verified that java.library.path contains /usr/local/mdsplus/lib

interestingly, jScope works fine.

Do you guys have any ideas for other things I should look for/test?

**Comment by tfredian** [comment]
It appears the fix for the jTraverser script was only done to the alpha branch so it has not been applied to the stable releases. I'll look into fixing this in the stable branch.

**Comment by gjhartwell** [comment]
Hi Tom,
That would be appreciated.
Thanks,
Greg

**Comment by tfredian** [comment]
Greg, when you get a chance can you try the latest stable release of MDSplus to see if this problem is now fixed?

**Comment by gjhartwell** [comment]
Hi Tom,
 jTraverser works now!  Thanks for checking into so promptly.

I did note an error (I think) on the install.  Not sure if it is a problem or not. Here is the snippet:
.
.
Setting up mdsplus-python(7.7.8) ...
find: '%{python_sitelib}' : No such file or directory
.
.
