### ISSUE TITLE
New bug with mdsobjects Alpha 7.15-5 Anaconda3 Python 3.6 Win 10 64-bit

### ISSUE THREAD

**Issue by alkhwarizmi** [MDSplus/mdsplus#996]
Dear all,

this morning i tried to upgrade the MDSplus installation on my PC (to solve a problem with Alpha 7.8.0). Afterwards, I started to receive an error message (not related to what I was trying to solve) which should be easily reproduced with the following snippet:

```python
from MDSplus import Tree
runNumber = 201701
treeName = "localtest"
tree = Tree(treeName, runNumber)
Traceback (most recent call last):
  File "<ipython-input-4-e907c1b18d5f>", line 1, in <module>
    tree = Tree(treeName, runNumber)
  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 317, in __init__
    _exc.checkStatus(_TreeShr._TreeOpen(_C.byref(self.ctx),
AttributeError: module 'MDSplus.mdsExceptions.treeshrExceptions' has no attribute 'checkStatus'
```
Is it a regression?

Sincerely,

**Comment by alkhwarizmi** [comment]
I confirm that this happens also with Stable 7.7.5.

I worked around the problem deleting the directory mdsException (well, just renamed to \_\_mdsExceptions\_\_).

I think that Python can't discriminate between the file `mdsExceptions.py` and the sister directory `mdsExceptions`, as the latter is also a package (there is an `__init__.py` file inside it)

Sincerely,
  Anton

**Comment by alkhwarizmi** [comment]
Closing this because after a complete and sound re-installation of the latest (7.15.7) version of MDSplus (remember to stop running services before uninstalling, see #998) the `mdsException` directory does not appear any more.
