### ISSUE TITLE
Problem with Alpha 7.15.5 and Stable 7.7.5 on Windows Server 2012 R2 Standard 64bit

### ISSUE THREAD

**Issue by alkhwarizmi** [MDSplus/mdsplus#998]
Dear all,

trying to use code perfectly working on Win10 64bit machine (used since months as data server) I run into big problems. I tried after upgrading MDSplus to new versions, I don't know if previously it would have worked.

Even the simplest operation (after deletion of mdsException directory, otherwise the error was #996) seems broken
```
from MDSplus import Tree

tree = Tree("inspire", -1, "new")

tree.addNode("EMN","STRUCTURE")
Traceback (most recent call last):

  File "<ipython-input-3-59e48e332ab9>", line 1, in <module>
    tree.addNode("EMN","STRUCTURE")

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 601, in addNode
    return TreeNode(nid.value,self)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 992, in __new__
    if node.usage == "DEVICE":

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 236, in __eq__
    return _cmp.EQ(self,y).evaluate().bool()

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 445, in evaluate
    return TdiEvaluate(self,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 71, in TdiEvaluate
    return _TdiShrFun(_TdiShr.TdiEvaluate,"Error evaluating",expression,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 52, in _TdiShrFun
    _exc.checkStatus(function(*rargs))

OSError: exception: access violation writing 0x00000000A320B5C0
```

Any ideas of what could it be?

Sincerely,

**Comment by tfredian** [comment]
I tried reproducing this on my WINDOWS10 64-bit system and it seemed to work fine:

`>>> from MDSplus import Tree`
`>>> tree=Tree("twf2",-1,"new")`
`>>> tree.addNode("EMN","STRUCTURE")`
`\TWF2::TOP.EMN`
`>>> import MDSplus`
`>>> MDSplus.__version__`
`'7.15.5'`
`>>> MDSplus.__file__`
`'c:\\ProgramData\\Anaconda3\\lib\\site-packages\\mdsplus_alpha-7.15.5-py3.6.egg\\MDSplus\\__init__.py'`

Is it possible that your Windows system had a very old MDSplus installation (6.n or earlier) prior to upgrading? Prior to the 7.n releases the installation kits were generated by Visual Studio but now they are built on linux using MinGW64 and use a different installer which will uninstall older versions of 7.n+ versions but does not detect the VS installs. Upgrading from the VS installers to the new installers requires manually uninstalling the VS MDSplus package before installing the newer release. If this is the cause of the problem you should open up Program and Features in the Control Panel and deinstall any MDSplus packages it lists and then reinstall the latest version.

There should be no difference in behavior on Windows10 or Windows Server 2012 R2.

**Comment by alkhwarizmi** [comment]
Thank you Tom,

the server runs on a virtual machine, and has been created a year ago. I doubt we installed an MDSplus version earlier than 7.0 but I will try to check.

The behaviour of MDSplus is currently very different, as on my PC the code runs, while on the server it does not.

Sincerely,

**Comment by alkhwarizmi** [comment]
Hi again Tom,

there was the same versin of the VC runtima installedd multiple times. I did the following operations:

1) Uninstalled all the VC runtimes
2) Uninstalled MDSplus
3) Reinstalled MDSplus alpha 7.15.5
4) Modified traverser.bat to work
5) Checked, with my surprise, that this time the mdsException directory in the Python distribution was not installed, so I did not have to remove it manually
6) Rebooted the machine

Unfortunately this didn't solve the problem. From IPython I get:
```
import MDSplus

MDSplus.__version__
Out[3]: '7.15.5'

MDSplus.__file__
Out[4]: 'C:\\Anaconda3\\lib\\site-packages\\mdsplus_alpha-7.15.5-py3.6.egg\\MDSplus\\__init__.py'

t = MDSplus.Tree("inspire", -1)

t.getNode("RAW.EH01:AI1")
Traceback (most recent call last):

  File "<ipython-input-7-3efd44b910a2>", line 1, in <module>
    t.getNode("RAW.EH01:AI1")

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 735, in getNode
    return TreeNode(int(n.value),self)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 992, in __new__
    if node.usage == "DEVICE":

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 236, in __eq__
    return _cmp.EQ(self,y).evaluate().bool()

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 445, in evaluate
    return TdiEvaluate(self,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 71, in TdiEvaluate
    return _TdiShrFun(_TdiShr.TdiEvaluate,"Error evaluating",expression,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 52, in _TdiShrFun
    _exc.checkStatus(function(*rargs))

OSError: exception: access violation writing 0x0000000016A1B380
```
but the model is show correctly by the jTraverser on the server:

![image](https://user-images.githubusercontent.com/5898559/29072531-59468348-7c48-11e7-8ef1-fe3b4651365c.png)

This is the list of the installed software in the machine:

![image](https://user-images.githubusercontent.com/5898559/29072578-882ad920-7c48-11e7-9ec5-927a5537caac.png)

Could it be a problem with Python bindings?

Sincerely,

**Comment by tfredian** [comment]
Thanks for the detailed report! We are trying to find a WS 2012 R2 to use to diagnose this problem. Based on the traceback I may have something to test if you have access to the python code on the system and can modify it. If you can edit: 

C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py

on your system, try modifying line 49 (approx) which contains a "_C.c_void_p(-1)" replacing that part to be "_C.c_void_p(0xffffffff)". Once this is done, retry your test to see if this fixes the problem. If it does we'll try to get a new release out asap. If not, we'll try to reproduce the problem here and hopefully find a fix for it.

-tom

**Comment by alkhwarizmi** [comment]
Dear Tom,

I tried to modify line 49 of `mdsdata.py` which now reads
```
    rargs = list(map(Data.byref,dargs))+[xd.byref,_C.c_void_p(0xffffffff)]
```
but nothing changes. To be sure I also deleted the corresponding .pyc file from \_\_pycache\_\_ directory, but also no changes. The error keeps to be this one:

```
from MDSplus import Tree

t = Tree("inspire", -1)

t.getNode("RAW.EH01:AI1")
Traceback (most recent call last):

  File "<ipython-input-4-3efd44b910a2>", line 1, in <module>
    t.getNode("RAW.EH01:AI1")

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 735, in getNode
    return TreeNode(int(n.value),self)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 992, in __new__
    if node.usage == "DEVICE":

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 236, in __eq__
    return _cmp.EQ(self,y).evaluate().bool()

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 445, in evaluate
    return TdiEvaluate(self,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 71, in TdiEvaluate
    return _TdiShrFun(_TdiShr.TdiEvaluate,"Error evaluating",expression,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 52, in _TdiShrFun
    _exc.checkStatus(function(*rargs))

OSError: exception: access violation writing 0x00000000C8FDB040
```

I have access to this machine so if you need some more testing I can do it.

Sincerely,

**Comment by tfredian** [comment]
Sorry it didn't help. We have fired up a WS2012 R2 system on an amazon ec2 server and installed MDSplus and anaconda3 and unfortunately, that is working perfectly. Josh created a new tree, added a node and successfully did a getNode('newnode') with it. We're still exploring though.

**Comment by alkhwarizmi** [comment]
I tried to make  a null pointer to void (0x0).
It seems that the underlying library is really trying to access the memory at the pointed value.

I am wondering now how can you generate a valid memory access to a had written location? What was the purpose of -1 (or 0xffffffffffffffff)?

Sincerely,

Modifications to `mdsdata.py`
```
    rargs = list(map(Data.byref,dargs))+[xd.byref,_C.c_void_p(0x0)]
    print(rargs)
```
stack trace
```
from MDSplus import Tree

t = Tree("inspire", -1)

t.getNode("RAW.EH01:AI1")
[<cparam 'P' (0000004D67B7ACE0)>, <cparam 'P' (0000004D6A8F03C0)>, c_void_p(None)]
Traceback (most recent call last):

  File "<ipython-input-3-3efd44b910a2>", line 1, in <module>
    t.getNode("RAW.EH01:AI1")

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 735, in getNode
    return TreeNode(int(n.value),self)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 992, in __new__
    if node.usage == "DEVICE":

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 237, in __eq__
    return _cmp.EQ(self,y).evaluate().bool()

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 446, in evaluate
    return TdiEvaluate(self,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 72, in TdiEvaluate
    return _TdiShrFun(_TdiShr.TdiEvaluate,"Error evaluating",expression,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 53, in _TdiShrFun
    _exc.checkStatus(function(*rargs))

OSError: exception: access violation reading 0x000000000000002B
```

**Comment by alkhwarizmi** [comment]
With `0xffffffffffffffff`

```
from MDSplus import Tree

t = Tree("inspire", -1)

t.getNode("RAW.EH01:AI1")
[<cparam 'P' (0000007D54FE1780)>, <cparam 'P' (0000007D57D603C0)>, c_void_p(18446744073709551615)]
Traceback (most recent call last):

  File "<ipython-input-3-3efd44b910a2>", line 1, in <module>
    t.getNode("RAW.EH01:AI1")

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 735, in getNode
    return TreeNode(int(n.value),self)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 992, in __new__
    if node.usage == "DEVICE":

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 237, in __eq__
    return _cmp.EQ(self,y).evaluate().bool()

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 446, in evaluate
    return TdiEvaluate(self,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 72, in TdiEvaluate
    return _TdiShrFun(_TdiShr.TdiEvaluate,"Error evaluating",expression,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 53, in _TdiShrFun
    _exc.checkStatus(function(*rargs))

OSError: exception: access violation writing 0x000000004E5BB0E0
```
With `0x000000ffffffffff`
```
from MDSplus import Tree

t = Tree("inspire", -1)

from MDSplus import Tree

t.getNode("RAW.EH01:AI1")
[<cparam 'P' (000000EB8BA3B190)>, <cparam 'P' (000000EB8E7803C0)>, c_void_p(1099511627775)]
Traceback (most recent call last):

  File "<ipython-input-4-3efd44b910a2>", line 1, in <module>
    t.getNode("RAW.EH01:AI1")

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 735, in getNode
    return TreeNode(int(n.value),self)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 992, in __new__
    if node.usage == "DEVICE":

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 237, in __eq__
    return _cmp.EQ(self,y).evaluate().bool()

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 446, in evaluate
    return TdiEvaluate(self,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 72, in TdiEvaluate
    return _TdiShrFun(_TdiShr.TdiEvaluate,"Error evaluating",expression,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 53, in _TdiShrFun
    _exc.checkStatus(function(*rargs))

OSError: exception: access violation reading 0x0000010000000002```

**Comment by alkhwarizmi** [comment]
I think I will try to remove and reinstall anaconda completely.
I let you know.

Sincerely,

**Comment by tfredian** [comment]
The routines such as TdiExecute in libTdiShr take a descriptor structure of a string of the tdi expression as the first argument and then a variable length number of arguments which are pointers to descriptors or NULL pointers designating the argument is missing. This list of pointers is terminated by a reserved pointer value of the low 32-bits all set and the high 32-bits clear on 64-bit platforms.

Can you try a couple more python tests:

>>> from MDSplus import Data
>>> x=Data('42')
>>> x=Data('$',42)
>>> x=Data('$','testing')

The failure you are getting is when a libTdiShr routine is being called with a string argument as one of the optional arguments. We were wondering if there might be a problem with just string arguments or any libTdiShr call.

**Comment by alkhwarizmi** [comment]
Dear Tom,

I have uninstalled Anaconda3 completely and reinstalled it from scratch.
Unfortunately, this also does not solve the problem.

Sincerely,

```
from MDSplus import Tree

t = Tree("inspire", -1)

t.getNode("RAW.EH01:AI1")
Traceback (most recent call last):

  File "<ipython-input-3-3efd44b910a2>", line 1, in <module>
    t.getNode("RAW.EH01:AI1")

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 735, in getNode
    return TreeNode(int(n.value),self)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\tree.py", line 992, in __new__
    if node.usage == "DEVICE":

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 236, in __eq__
    return _cmp.EQ(self,y).evaluate().bool()

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 445, in evaluate
    return TdiEvaluate(self,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 71, in TdiEvaluate
    return _TdiShrFun(_TdiShr.TdiEvaluate,"Error evaluating",expression,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 52, in _TdiShrFun
    _exc.checkStatus(function(*rargs))

OSError: exception: access violation writing 0x000000002471B360
```

**Comment by alkhwarizmi** [comment]
Hello Tom,

the first command works, not the other two

```
from MDSplus import Data

x=Data('42')

x=Data('$',42)
Traceback (most recent call last):

  File "<ipython-input-3-2c094239f834>", line 1, in <module>
    x=Data('$',42)

TypeError: __init__() takes 2 positional arguments but 3 were given


x=Data('$','testing')
Traceback (most recent call last):

  File "<ipython-input-4-d050999c814f>", line 1, in <module>
    x=Data('$','testing')

TypeError: __init__() takes 2 positional arguments but 3 were given
```

Sincerely,

**Comment by tfredian** [comment]
Sorry. My fault for the last tests. I meant to type:

x=Data.execute('42')
x=Data.execute('$',42)
x=Data.execute('$','testing')

Thanks,
Tom

**Comment by alkhwarizmi** [comment]
Hi Tom,

none of them works.

sincerely,

```
x=Data.execute('42')
Traceback (most recent call last):

  File "<ipython-input-19-e90e0b37a9e1>", line 1, in <module>
    x=Data.execute('42')

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 438, in execute
    return TdiExecute(*args,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 63, in TdiExecute
    return _TdiShrFun(_TdiShr.TdiExecute,"Error executing",expression,*args,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 52, in _TdiShrFun
    _exc.checkStatus(function(*rargs))

OSError: exception: access violation writing 0x00000000EB24B1E0


x=Data.execute('$',42)
Traceback (most recent call last):

  File "<ipython-input-20-ba79b324e8a7>", line 1, in <module>
    x=Data.execute('$',42)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 438, in execute
    return TdiExecute(*args,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 63, in TdiExecute
    return _TdiShrFun(_TdiShr.TdiExecute,"Error executing",expression,*args,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 52, in _TdiShrFun
    _exc.checkStatus(function(*rargs))

OSError: exception: access violation writing 0x00000000EB24B200


x=Data.execute('$','testing')
Traceback (most recent call last):

  File "<ipython-input-21-11acb9cad91a>", line 1, in <module>
    x=Data.execute('$','testing')

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 438, in execute
    return TdiExecute(*args,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 63, in TdiExecute
    return _TdiShrFun(_TdiShr.TdiExecute,"Error executing",expression,*args,**kwargs)

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.15.5-py3.6.egg\MDSplus\mdsdata.py", line 52, in _TdiShrFun
    _exc.checkStatus(function(*rargs))

OSError: exception: access violation writing 0x00000000EB24B2C0
```

**Comment by tfredian** [comment]
One thing very curious about your error stack. What version of anaconda3 do you have installed and is it 64-bit? On both my Windows 10 system and the new WS2012 R2 systems we installed the latest 64-bit anaconda3 and the MDSplus module gets installed in a different location:

    PS C:\Users\Administrator> python
    Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import MDSplus
    >>> MDSplus.__file__
    'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\mdsplus_alpha-7.15.6-
    py3.6.egg\\MDSplus\\__init__.py'
    >>>

**Comment by alkhwarizmi** [comment]
Hi Tom,

previously I had an old version (Python 3.4) of it which I had upgraded to Python 3.6 manually.

Today after lunch I removed it and re-installed the latest distribution.

The suggested install directory was C:\ProgramData\Anaconda3 but I changed to C:\Anaconda3 to make the path of things shorter.

Is ProgramData a kind of special directory for windows server? I installed MDSplus under C:\MDSplus for the same reasons...

Sincerely,

**Comment by tfredian** [comment]
So your anaconda comes up with the same version info as in my last post? It shouldn't matter that you didn't install in the default locations. I just wondered if it was a different version.

**Comment by alkhwarizmi** [comment]
No it is different!

```
(C:\Anaconda3) C:\MDSplus\mdsobjects\python>python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import MDSplus
>>> MDSplus.__version__
'7.15.5'
>>> MDSplus.__file__
'C:\\Anaconda3\\lib\\site-packages\\mdsplus_alpha-7.15.5-py3.6.egg\\MDSplus\\__init__.py'
```

Did you update MDSplus in the meanwhile?

**Comment by tfredian** [comment]
I was referring to the anaconda being used and that appears to be the same. It is very peculiar that your Windows Server is having this problem but Windows 10 and our same Windows Server 2012 R2 works fine!
We might have to put some debug printouts in a tdishr.dll to diagnose the problem. It is possible to install a mingw64 gdb on the system and debug it but it can be complicated.

**Comment by alkhwarizmi** [comment]
Are these options ok?


![image](https://user-images.githubusercontent.com/5898559/29090841-274bc4e6-7c81-11e7-8be6-260bd7fc1635.png)

**Comment by alkhwarizmi** [comment]
I have a Xeon processor so I opted for x86_64 architecture, posix threading, SEH exceptions and latest build version (1).

Let me know what I can do to start well tomorrow.

Sincerely,

**Comment by joshStillerman** [comment]
I could be wrong but I think putting MDSplus not in the default location 
is problematic.  It may be OK if you add that directory to your system 
PATH.  When I was installing on Windoz server this morning, the mdsplus 
python install did not work until python was in the system path too.  
 From how far you are getting, these things are probably not your 
issue.  For the record the sequence that worked for me on a bare system:

1 - install anaconda (python 3, ,64 bit), choose the not recommended 
option - add anaconda to system path

2 - install mdsplus (current alpha)  and include python

So you could:

1 - uninstall mdsplus

2 - uninstall anaconda

then do the steps above.  I did not need to install mingw.

-Josh

**Comment by tfredian** [comment]
One thing I thought of last night... Do you have any mdsip services running on this system? If so, there is a possibility that the new MDSplus installation did not replace some of the core MDSplus libraries if these services were running. You might check the date of C:\WINDOWS\SYSTEM32\TDISHR.DLL and see if it predates when you did the MDSplus install. If it does I would suggest stopping the mdsip services and reinstalling MDSplus. 

If the libraries look ok then you can try to use gdb to debug the problem. To do this you first start python and then get its pid number using task manager. Then you can run gdb --pid=<pid> on the python process. When the accvio occurs gdb should provide a traceback so we can find the line in tdishr where the access violation is occuring.

We may want to continue this conversation outside of github at some point soon.

**Comment by alkhwarizmi** [comment]
Dear Tom,

let me post this last message on gitHub as there is a positive resolution of this ticket.

In short, it seems that the only thing to do is to install MDSplus after having stopped the MDSplus Action and Data Server services.

However, I didn't noticed any warning messages from the uninstaller nor from the installer about the impossibility to delete or copy a certain file. This information could be helpful to point the user in the right direction. Even better if the uninstaller could check and stop the services itself before deleting the files.

For the records, the sequence that lead me to the heaven of a working installation was:

1) Uninstall MDSplus (was under C:\Program Files\MDSplus)
2) Delete manually the bin directory and dll files (btw where is it now?)
3) Uninstall Anaconda3 (was under C:\ProgramData\MDSplus)
4) Stop the services MDSplus Data and Action Server
5) Install Anaconda3 in C:\Anaconda3 with the options "add anaconda to path" and "register anaconda as default system Python"
6) Install MDSplus in C:\MDSplus
7) Start the services MDSplus Data and Action Server

Unfortunately I didn't look to the file C:\WINDOWS\SYSTEM32\TDISHR.DLL so I can't tell if that was involved by the problem.

Having said this, I thank you for the patience and the help that pointed me in the right direction. I have really appreciated.

Sincerely,

**Comment by tfredian** [comment]
Fantastic! Sorry for all the trouble. The MDSplus dll's are now installed in C:\WINDOWS\SYSTEM32 (64-bit) and C:\WINDOWS\SYSWOW64 (32-bit). This was done a while ago to avoid all the issues with apps finding the libraries. I'll have to revisit the installer builder we're now using (makensis) to see if it is possible to display a warning if it can't uninstall dll's if they are currently in use. The same issue probably occurs if someone happens to be running any MDSplus app on the server. I'm so glad it didn't turn out to be some complicated Windows configuration issue.
